version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8089:80"
        volumes:
            - .:/var/html/udemy
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php
        volumes:
            - .:/var/html/udemy

    redis:
        image: redis:3.0
        volumes:
            - ./docker/redis/data:/data

    db:
        image: postgres:12.6
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: pguser
            POSTGRES_DB: pgdb
